name = "qtrnn"
license = "MIT"
licenselink = "https://git.sr.ht/~mdkcore/qtrnn-hugo-theme/tree/master/LICENSE.md"
description = "Minimal theme for Hugo."
homepage = "https://git.sr.ht/~mdkcore/qtrnn-hugo-theme"
tags = ["blog", "minimal", "monospace", "dark mode", "simple", "clean", "light", "responsive", "fast", "no-js", "no-tracking", "privacy"]
features = ["blog", "privacy", "responsive", "fast"]
min_version = "0.20"

[author]
  name = "mdkcore"
  homepage = "qtrnn.io"

[original]
  author = "colorchestra"
  homepage = "https://github.com/colorchestra"
  repo = "https://github.com/colorchestra/smol"
